export enum Industry  {
    HEALTHCARE = "HEALTHCARE",
    AGRICULTURE = "AGRICULTURE",
    AUTOMOBILE = "AUTOMOBILE",
    BANKING = "BANKING",
    CONSTRUCTION  = "CONSTRUCTION",
    EDUCATION = 'EDUCATION',
}